image: Visual Studio 2017

before_build:
  - ps: Update-AppveyorBuild -Version "$(Get-Content VERSION).build.$env:APPVEYOR_BUILD_NUMBER"

build_script:
  - ps: src\build.ps1
  - ps: release\build.ps1 -GitHubRelease:$($env:APPVEYOR_REPO_TAG -eq "true")

artifacts:
  - path: release\*.xml
  - path: release\*.tar.gz
  - path: build\Bootstrap
    name: bootstrap
  - path: build\0install.*.nupkg
    name: powershell
  - path: build\*.symbols.nupkg
    name: symbols

deploy:
  - provider: Environment
    name: GitHub Releases
    on:
      appveyor_repo_tag: true
  - provider: Environment
    name: PowerShell Gallery
    on:
      appveyor_repo_tag: true
  - provider: Environment
    name: SymbolSource
    on:
      appveyor_repo_tag: true
