image: Visual Studio 2017

before_build:
  - gitversion /l console /output buildserver

build_script:
  - ps: src\build.ps1 $env:GitVersion_NuGetVersion
  - ps: release\build.ps1 $env:GitVersion_NuGetVersion

artifacts:
  - path: release\*.xml
  - path: release\*.tar.gz
  - path: artifacts\Bootstrap\0install
    name: 0install
  - path: artifacts\Bootstrap\zero-install
    name: zero-install
  - path: artifacts\Bootstrap\PowerShell\0install.*.nupkg
    name: powershell

deploy:
  - provider: Environment
    name: GitHub Releases
    on:
      appveyor_repo_tag: true
  - provider: Environment
    name: PowerShell Gallery
    on:
      appveyor_repo_tag: true
