image: Visual Studio 2017

before_build:
  - ps: Update-AppveyorBuild -Version "$(Get-Content VERSION).build.$env:APPVEYOR_BUILD_NUMBER"

build_script:
  - ps: src\build.ps1
  - ps: doc\build.ps1
  - ps: release\build.ps1

test_script:
  - ps: src\test.ps1

artifacts:
  - path: release\ZeroInstall-*.*
    name: Feeds
  - path: build\Bootstrap
    name: Bootstrap
  - path: build\0install.*.nupkg
    name: PowerShellModules
  - path: build\*.symbols.nupkg
    name: Symbols
  - path: build\Documentation
    name: Documentation

deploy:
  - provider: Environment
    name: github.com
    on:
      appveyor_repo_tag: true
  - provider: Environment
    name: PowerShellGallery.com
    on:
      appveyor_repo_tag: true
  - provider: Environment
    name: SymbolSource.org
    on:
      appveyor_repo_tag: true
