image: Visual Studio 2019

cache:
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'

before_build:
  - ps: .\0install.ps1 run https://apps.0install.net/devel/gitversion.xml /l console /output buildserver

build_script:
  - ps: src\build.ps1 $env:GitVersion_NuGetVersion

after_build:
  - artifacts\Release\net45\win\0install.exe self deploy --batch

artifacts:
  - path: artifacts

deploy:
  - provider: Webhook
    url: https://app.signpath.io/API/v1/0e70cf92-49a1-4427-a800-b6bc5b497936/Integrations/AppVeyor?ProjectSlug=win&SigningPolicySlug=release-signing
    authorization:
       secure: 1lrrvByUN3qR7P/QQN6XXy4LWmh8ls/veOESoeVffvyF4kOqo28JxoZtIxYOZZpAZKlbAv8tWQaLFZiUxXFHmA==
    on:
      appveyor_repo_tag: true
