image: Visual Studio 2019

cache:
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'
  - '%LOCALAPPDATA%\0install.net'
  - '%APPDATA%\0install.net'

before_build:
  - choco install GitVersion.Portable --version 4.0.0
  - gitversion /l console /output buildserver

build_script:
  - ps: src\build.ps1 $env:GitVersion_NuGetVersion
  - ps: feed\build.ps1 $env:GitVersion_NuGetVersion

artifacts:
  - path: feed\*.xml
  - path: feed\*.tar.gz
  - path: artifacts\Bootstrap
  - path: artifacts\0install.chocolatey.*.nupkg
  - path: artifacts\0install.powershell.*.nupkg

deploy:
  - provider: Environment
    name: GitHub Releases
    on:
      appveyor_repo_tag: true
  - provider: Environment
    name: Chocolatey
    on:
      appveyor_repo_tag: true
  - provider: Environment
    name: PowerShell Gallery
    on:
      appveyor_repo_tag: true
