image: Visual Studio 2022

cache:
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj,**\*.targets,**\*.props'

before_build:
  - powershell .\0install.ps1 run --batch https://apps.0install.net/devel/gitversion.xml /l console /output buildserver

build_script:
  - powershell .\build.ps1 %GitVersion_NuGetVersion%

test_script:
  - powershell .\test.ps1 -Purge
  - powershell .\test.ps1 -Deploy -Purge
  - powershell .\test.ps1 -Deploy -Machine -Purge
  - powershell .\test.ps1 -Deploy -Portable -Purge

artifacts:
  - path: artifacts

deploy:
  - provider: Webhook
    url: https://app.signpath.io/API/v1/0e70cf92-49a1-4427-a800-b6bc5b497936/Integrations/AppVeyor?ProjectSlug=win&SigningPolicySlug=release-signing
    authorization:
       secure: 1lrrvByUN3qR7P/QQN6XXy4LWmh8ls/veOESoeVffvyF4kOqo28JxoZtIxYOZZpAZKlbAv8tWQaLFZiUxXFHmA==
    on:
      appveyor_repo_tag: true
