image: Visual Studio 2019

cache:
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'

before_build:
  - choco install GitVersion.Portable --version 4.0.0
  - gitversion /l console /output buildserver

build_script:
  - ps: src\build.ps1 $env:GitVersion_NuGetVersion

artifacts:
  - path: artifacts

deploy:
  - provider: Webhook
    url: https://app.signpath.io/API/v1/0e70cf92-49a1-4427-a800-b6bc5b497936/Integrations/AppVeyor?ProjectSlug=win&SigningPolicySlug=release-signing
    authorization:
       secure: 1lrrvByUN3qR7P/QQN6XXy4LWmh8ls/veOESoeVffvyF4kOqo28JxoZtIxYOZZpAZKlbAv8tWQaLFZiUxXFHmA==
    #on:
    #  appveyor_repo_tag: true
