image: Visual Studio 2017

cache:
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'

before_build:
  - gitversion /l console /output buildserver

build_script:
  - ps: src\build.ps1 $env:GitVersion_NuGetVersion
  - ps: feed\build.ps1 $env:GitVersion_NuGetVersion

artifacts:
  - path: feed\*.xml
  - path: feed\*.tar.gz
  - path: artifacts\Bootstrap\0install
    name: 0install
  - path: artifacts\Bootstrap\zero-install
    name: zero-install
  - path: artifacts\Bootstrap\0install.chocolatey.*.nupkg
    name: chocolatey
  - path: artifacts\Bootstrap\0install.powershell.*.nupkg
    name: powershell

deploy:
  - provider: Environment
    name: GitHub Releases
    on:
      appveyor_repo_tag: true
  - provider: Environment
    name: Chocolatey
    on:
      appveyor_repo_tag: true
  - provider: Environment
    name: PowerShell Gallery
    on:
      appveyor_repo_tag: true
