//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroInstall.Central.WinForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZeroInstall.Central.WinForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AddButton {
            get {
                object obj = ResourceManager.GetObject("AddButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to &quot;my applications&quot;.
        /// </summary>
        internal static string AddButtonTooltip {
            get {
                return ResourceManager.GetString("AddButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap App {
            get {
                object obj = ResourceManager.GetObject("App", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove &apos;{0}&apos; from your application list?
        ///This will also remove any desktop integration applied for this application..
        /// </summary>
        internal static string AppRemoveConfirm {
            get {
                return ResourceManager.GetString("AppRemoveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowDown {
            get {
                object obj = ResourceManager.GetObject("ArrowDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowRight {
            get {
                object obj = ResourceManager.GetObject("ArrowRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowUp {
            get {
                object obj = ResourceManager.GetObject("ArrowUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the URL or local file path of the feed catalog to add:.
        /// </summary>
        internal static string EnterCatalogUrl {
            get {
                return ResourceManager.GetString("EnterCatalogUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the URL of a Zero Install interface here:.
        /// </summary>
        internal static string EnterInterfaceUrl {
            get {
                return ResourceManager.GetString("EnterInterfaceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to run {0}..
        /// </summary>
        internal static string FailedToRun {
            get {
                return ResourceManager.GetString("FailedToRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring duplicate application list entry for &apos;{0}&apos;..
        /// </summary>
        internal static string IgnoringDuplicateAppListEntry {
            get {
                return ResourceManager.GetString("IgnoringDuplicateAppListEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common app.
        /// </summary>
        internal static string IntroCommonApp {
            get {
                return ResourceManager.GetString("IntroCommonApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does the usual stuff.
        /// </summary>
        internal static string IntroCommonAppSummary {
            get {
                return ResourceManager.GetString("IntroCommonAppSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cool app.
        /// </summary>
        internal static string IntroCoolApp {
            get {
                return ResourceManager.GetString("IntroCoolApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does something cool.
        /// </summary>
        internal static string IntroCoolAppSummary {
            get {
                return ResourceManager.GetString("IntroCoolAppSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other app.
        /// </summary>
        internal static string IntroOtherApp {
            get {
                return ResourceManager.GetString("IntroOtherApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does something else.
        /// </summary>
        internal static string IntroOtherAppSummary {
            get {
                return ResourceManager.GetString("IntroOtherAppSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you like an app,
        ///add it to &quot;My applications&quot;..
        /// </summary>
        internal static string IntroSubtitlesAddApp {
            get {
                return ResourceManager.GetString("IntroSubtitlesAddApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just search for an app in the &quot;Catalog&quot;....
        /// </summary>
        internal static string IntroSubtitlesCatalogSearch {
            get {
                return ResourceManager.GetString("IntroSubtitlesCatalogSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Integrate&quot; an app to put it
        ///in the start menu or on the desktop..
        /// </summary>
        internal static string IntroSubtitlesIntegrateApp {
            get {
                return ResourceManager.GetString("IntroSubtitlesIntegrateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can manage your list of favorite apps here..
        /// </summary>
        internal static string IntroSubtitlesMyApps {
            get {
                return ResourceManager.GetString("IntroSubtitlesMyApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... and run it!.
        /// </summary>
        internal static string IntroSubtitlesRunApp {
            get {
                return ResourceManager.GetString("IntroSubtitlesRunApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have fun!.
        /// </summary>
        internal static string IntroSubtitlesThanks {
            get {
                return ResourceManager.GetString("IntroSubtitlesThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Zero Install you don&apos;t have to install apps..
        /// </summary>
        internal static string IntroSubtitlesWelcome {
            get {
                return ResourceManager.GetString("IntroSubtitlesWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine-wide mode.
        /// </summary>
        internal static string MachineWideMode {
            get {
                return ResourceManager.GetString("MachineWideMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ModifyButton {
            get {
                object obj = ResourceManager.GetObject("ModifyButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify integration.
        /// </summary>
        internal static string ModifyButtonTooltip {
            get {
                return ResourceManager.GetString("ModifyButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No
        ///Keep the application.
        /// </summary>
        internal static string NoKeepApp {
            get {
                return ResourceManager.GetString("NoKeepApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing these options may prevent Zero Install from working correctly. Are you sure you want to continue?.
        /// </summary>
        internal static string OptionsAdvancedWarn {
            get {
                return ResourceManager.GetString("OptionsAdvancedWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable mode.
        /// </summary>
        internal static string PortableMode {
            get {
                return ResourceManager.GetString("PortableMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem loading the options..
        /// </summary>
        internal static string ProblemLoadingOptions {
            get {
                return ResourceManager.GetString("ProblemLoadingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem saving the options..
        /// </summary>
        internal static string ProblemSavingOptions {
            get {
                return ResourceManager.GetString("ProblemSavingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove all entries from the list?.
        /// </summary>
        internal static string RemoveAllEntries {
            get {
                return ResourceManager.GetString("RemoveAllEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RemoveButton {
            get {
                object obj = ResourceManager.GetObject("RemoveButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from &quot;my applications&quot;.
        /// </summary>
        internal static string RemoveButtonTooltip {
            get {
                return ResourceManager.GetString("RemoveButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove the {0} checked keys from the list?.
        /// </summary>
        internal static string RemoveCheckedKeys {
            get {
                return ResourceManager.GetString("RemoveCheckedKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove the {0} selected entries from the list?.
        /// </summary>
        internal static string RemoveSelectedEntries {
            get {
                return ResourceManager.GetString("RemoveSelectedEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to save any changes made?.
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No
        ///Discard changes.
        /// </summary>
        internal static string SaveChangesNo {
            get {
                return ResourceManager.GetString("SaveChangesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes
        ///Save changes.
        /// </summary>
        internal static string SaveChangesYes {
            get {
                return ResourceManager.GetString("SaveChangesYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select command for {0}.
        /// </summary>
        internal static string SelectCommand {
            get {
                return ResourceManager.GetString("SelectCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &amp;command.
        /// </summary>
        internal static string SelectCommandButton {
            get {
                return ResourceManager.GetString("SelectCommandButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &amp;version.
        /// </summary>
        internal static string SelectVersionButton {
            get {
                return ResourceManager.GetString("SelectVersionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update to Zero Install v{0} is available. Install now? (recommended).
        /// </summary>
        internal static string SelfUpdateAvailable {
            get {
                return ResourceManager.GetString("SelfUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No
        ///Ignore update for now.
        /// </summary>
        internal static string SelfUpdateNo {
            get {
                return ResourceManager.GetString("SelfUpdateNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes
        ///Install update.
        /// </summary>
        internal static string SelfUpdateYes {
            get {
                return ResourceManager.GetString("SelfUpdateYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SetupButton {
            get {
                object obj = ResourceManager.GetObject("SetupButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup integration.
        /// </summary>
        internal static string SetupButtonTooltip {
            get {
                return ResourceManager.GetString("SetupButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to complete Sync Setup first..
        /// </summary>
        internal static string SyncCompleteSetupFirst {
            get {
                return ResourceManager.GetString("SyncCompleteSetupFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username and/or password you entered are incorrect..
        /// </summary>
        internal static string SyncCredentialsInvalid {
            get {
                return ResourceManager.GetString("SyncCredentialsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The crypto key is used to encrypt your data locally before transmitting it to the server.
        ///Keep this key secret and use something different for your password. This way nobody can access your data, even if the server were to be compromised..
        /// </summary>
        internal static string SyncCryptoKeyDescription {
            get {
                return ResourceManager.GetString("SyncCryptoKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Crypto key you entered is incorrect..
        /// </summary>
        internal static string SyncCryptoKeyInvalid {
            get {
                return ResourceManager.GetString("SyncCryptoKeyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data currently stored on the Sync server is damaged.
        ///You can replace the data stored on the server by choosing that you don&apos;t remember the Crypto key..
        /// </summary>
        internal static string SyncServerDataDamaged {
            get {
                return ResourceManager.GetString("SyncServerDataDamaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will replace any existing Sync settings with new ones. Continue?.
        /// </summary>
        internal static string SyncWillReplaceConfig {
            get {
                return ResourceManager.GetString("SyncWillReplaceConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to download application catalog..
        /// </summary>
        internal static string UnableToDownloadCatalog {
            get {
                return ResourceManager.GetString("UnableToDownloadCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the application list..
        /// </summary>
        internal static string UnableToLoadAppList {
            get {
                return ResourceManager.GetString("UnableToLoadAppList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load feed for application list entry &apos;{0}&apos;..
        /// </summary>
        internal static string UnableToLoadFeedForApp {
            get {
                return ResourceManager.GetString("UnableToLoadFeedForApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load application icon..
        /// </summary>
        internal static string UnableToLoadIcon {
            get {
                return ResourceManager.GetString("UnableToLoadIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to perform self-update check..
        /// </summary>
        internal static string UnableToSelfUpdate {
            get {
                return ResourceManager.GetString("UnableToSelfUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to store application icon..
        /// </summary>
        internal static string UnableToStoreIcon {
            get {
                return ResourceManager.GetString("UnableToStoreIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to use an unencrypted connection to a Sync server?
        ///Encrypted connections use an https:// prefix..
        /// </summary>
        internal static string UnencryptedSyncServer {
            get {
                return ResourceManager.GetString("UnencryptedSyncServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will automatically remove implementations from the cache that are no longer needed after the update. Continue?
        ///Important: Applications you have &quot;Run&quot; previously without adding them to &quot;My applications&quot; will also be removed from the cache.  You will need to be online if you decide to run them again..
        /// </summary>
        internal static string UpdateAllCleanWillRemove {
            get {
                return ResourceManager.GetString("UpdateAllCleanWillRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Update.
        /// </summary>
        internal static string UpdateButton {
            get {
                return ResourceManager.GetString("UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working....
        /// </summary>
        internal static string Working {
            get {
                return ResourceManager.GetString("Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes
        ///Remove the application.
        /// </summary>
        internal static string YesRemoveApp {
            get {
                return ResourceManager.GetString("YesRemoveApp", resourceCulture);
            }
        }
    }
}
