//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroInstall.Store.Management.WinForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZeroInstall.Store.Management.WinForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All checked implementations are fine..
        /// </summary>
        internal static string AllImplementationsOK {
            get {
                return ResourceManager.GetString("AllImplementationsOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the {0} checked element(s) from the cache?.
        /// </summary>
        internal static string DeleteCheckedEntries {
            get {
                return ResourceManager.GetString("DeleteCheckedEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete his entry from the cache?.
        /// </summary>
        internal static string DeleteEntry {
            get {
                return ResourceManager.GetString("DeleteEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementation is fine..
        /// </summary>
        internal static string ImplementationOK {
            get {
                return ResourceManager.GetString("ImplementationOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, keep.
        /// </summary>
        internal static string NoKeep {
            get {
                return ResourceManager.GetString("NoKeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open in file manager.
        /// </summary>
        internal static string OpenInFileManager {
            get {
                return ResourceManager.GetString("OpenInFileManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable mode.
        /// </summary>
        internal static string PortableMode {
            get {
                return ResourceManager.GetString("PortableMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary directories.
        /// </summary>
        internal static string TemporaryDirectories {
            get {
                return ResourceManager.GetString("TemporaryDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown interface.
        /// </summary>
        internal static string UnknownInterface {
            get {
                return ResourceManager.GetString("UnknownInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        internal static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, delete.
        /// </summary>
        internal static string YesDelete {
            get {
                return ResourceManager.GetString("YesDelete", resourceCulture);
            }
        }
    }
}
