//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroInstall.Model.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZeroInstall.Model.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string must be in the form &quot;os-cpu&quot;..
        /// </summary>
        internal static string ArchitectureStringFormat {
            get {
                return ResourceManager.GetString("ArchitectureStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find command &apos;{0}&apos;..
        /// </summary>
        internal static string CommandNotFound {
            get {
                return ResourceManager.GetString("CommandNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading feed preferences for &apos;{0}&apos;. Reverting to default values..
        /// </summary>
        internal static string ErrorLoadingFeedPrefs {
            get {
                return ResourceManager.GetString("ErrorLoadingFeedPrefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading interface preferences for &apos;{0}&apos;. Reverting to default values..
        /// </summary>
        internal static string ErrorLoadingInterfacePrefs {
            get {
                return ResourceManager.GetString("ErrorLoadingInterfacePrefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find feed &apos;{0}&apos; in catalog..
        /// </summary>
        internal static string FeedNotInCatalog {
            get {
                return ResourceManager.GetString("FeedNotInCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find implementation for interface &apos;{0}&apos; in the selection..
        /// </summary>
        internal static string ImplementationNotInSelection {
            get {
                return ResourceManager.GetString("ImplementationNotInSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digest &apos;{0}&apos; is not in the form &apos;algorithm=value&apos;..
        /// </summary>
        internal static string InvalidDigest {
            get {
                return ResourceManager.GetString("InvalidDigest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The interface &apos;{0}&apos; is not a valid &apos;http(s):&apos; URI and is not a valid local path either..
        /// </summary>
        internal static string InvalidInterfaceID {
            get {
                return ResourceManager.GetString("InvalidInterfaceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing &apos;/&apos; after host name in URI &apos;{0}&apos;..
        /// </summary>
        internal static string MissingSlashInUri {
            get {
                return ResourceManager.GetString("MissingSlashInUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dot-separated list may only contain decimal numbers..
        /// </summary>
        internal static string MustBeDottedList {
            get {
                return ResourceManager.GetString("MustBeDottedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be a specific CPU (not &quot;All&quot; or &quot;Unknown&quot;)..
        /// </summary>
        internal static string MustBeSpecificCPU {
            get {
                return ResourceManager.GetString("MustBeSpecificCPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be a specific operating system (not &quot;All&quot; or &quot;Unknown&quot;)..
        /// </summary>
        internal static string MustBeSpecificOS {
            get {
                return ResourceManager.GetString("MustBeSpecificOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version number may only contain dot-separated decimals and modifier strings..
        /// </summary>
        internal static string MustBeValidVersionPart {
            get {
                return ResourceManager.GetString("MustBeValidVersionPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version number must begin with a list of dot-separated decimals..
        /// </summary>
        internal static string MustStartWithDottedList {
            get {
                return ResourceManager.GetString("MustStartWithDottedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No suitable icon was found..
        /// </summary>
        internal static string NoSuitableIconFound {
            get {
                return ResourceManager.GetString("NoSuitableIconFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buggy implementation.
        /// </summary>
        internal static string SelectionCandidateNoteBuggy {
            get {
                return ResourceManager.GetString("SelectionCandidateNoteBuggy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible operating system or CPU.
        /// </summary>
        internal static string SelectionCandidateNoteIncompatibleArchitecture {
            get {
                return ResourceManager.GetString("SelectionCandidateNoteIncompatibleArchitecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insecure implementation.
        /// </summary>
        internal static string SelectionCandidateNoteInsecure {
            get {
                return ResourceManager.GetString("SelectionCandidateNoteInsecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementation not in cache (currently in off-line mode).
        /// </summary>
        internal static string SelectionCandidateNoteNotCached {
            get {
                return ResourceManager.GetString("SelectionCandidateNoteNotCached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-executable source implementation.
        /// </summary>
        internal static string SelectionCandidateNoteSource {
            get {
                return ResourceManager.GetString("SelectionCandidateNoteSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementation version too old or too new.
        /// </summary>
        internal static string SelectionCandidateNoteVersionMismatch {
            get {
                return ResourceManager.GetString("SelectionCandidateNoteVersionMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown CPU..
        /// </summary>
        internal static string UnknownCpu {
            get {
                return ResourceManager.GetString("UnknownCpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown modifier..
        /// </summary>
        internal static string UnknownModifier {
            get {
                return ResourceManager.GetString("UnknownModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown operating system..
        /// </summary>
        internal static string UnknownOS {
            get {
                return ResourceManager.GetString("UnknownOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of version range must be exclusive. Use &apos;..!{0}&apos;, not &apos;..{0}&apos;..
        /// </summary>
        internal static string VersionRangeEndNotExclusive {
            get {
                return ResourceManager.GetString("VersionRangeEndNotExclusive", resourceCulture);
            }
        }
    }
}
