//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroInstall.Store.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZeroInstall.Store.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The archive file is invalid or damaged..
        /// </summary>
        internal static string ArchiveInvalid {
            get {
                return ResourceManager.GetString("ArchiveInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The archive contains invalid paths (potentially a security risk)..
        /// </summary>
        internal static string ArchiveInvalidPath {
            get {
                return ResourceManager.GetString("ArchiveInvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting implementation {0}.
        /// </summary>
        internal static string DeletingImplementation {
            get {
                return ResourceManager.GetString("DeletingImplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An implementation&apos;s manifest hash doesn&apos;t match the expected value!
        ///Expected value: {0}
        ///Actual value: {1}.
        /// </summary>
        internal static string DigestMismatch {
            get {
                return ResourceManager.GetString("DigestMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting archive ({0}).
        /// </summary>
        internal static string ExtractingArchive {
            get {
                return ResourceManager.GetString("ExtractingArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; could not be located in the feed cache. Looked for file at: {1}.
        /// </summary>
        internal static string FeedNotInCache {
            get {
                return ResourceManager.GetString("FeedNotInCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file to be signed could not be found..
        /// </summary>
        internal static string FileToSignNotFound {
            get {
                return ResourceManager.GetString("FileToSignNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating manifest ({0}).
        /// </summary>
        internal static string GeneratingManifest {
            get {
                return ResourceManager.GetString("GeneratingManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; is neither a symbolic link nor a regular file..
        /// </summary>
        internal static string IllegalFileType {
            get {
                return ResourceManager.GetString("IllegalFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The implementation &apos;{0}&apos; is already in the store..
        /// </summary>
        internal static string ImplementationAlreadyInStore {
            get {
                return ResourceManager.GetString("ImplementationAlreadyInStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following implementation could not be located: {0}.
        /// </summary>
        internal static string ImplementationNotFound {
            get {
                return ResourceManager.GetString("ImplementationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The underlying file system does not store file change times with sufficient accuracy.
        ///If you are using a FAT-formatted drive please convert it to NTFS..
        /// </summary>
        internal static string InsufficientFSTimeAccuracy {
            get {
                return ResourceManager.GetString("InsufficientFSTimeAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The manifest file contains invalid lines..
        /// </summary>
        internal static string InvalidLinesInManifest {
            get {
                return ResourceManager.GetString("InvalidLinesInManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of parts in line..
        /// </summary>
        internal static string InvalidNumberOfLineParts {
            get {
                return ResourceManager.GetString("InvalidNumberOfLineParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The signature is invalid or damaged..
        /// </summary>
        internal static string InvalidSignature {
            get {
                return ResourceManager.GetString("InvalidSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested URL is invalid..
        /// </summary>
        internal static string InvalidUrl {
            get {
                return ResourceManager.GetString("InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No path specified..
        /// </summary>
        internal static string MissingPath {
            get {
                return ResourceManager.GetString("MissingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file or directory name must not contain a newline character..
        /// </summary>
        internal static string NewlineInName {
            get {
                return ResourceManager.GetString("NewlineInName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No known digest method was defined..
        /// </summary>
        internal static string NoKnownDigestMethod {
            get {
                return ResourceManager.GetString("NoKnownDigestMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number value is too large..
        /// </summary>
        internal static string NumberTooLarge {
            get {
                return ResourceManager.GetString("NumberTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path should be relative..
        /// </summary>
        internal static string PathNotRelative {
            get {
                return ResourceManager.GetString("PathNotRelative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New feed&apos;s modification time is before old version!
        ///Feed ID: {0}
        ///Old time: {1}
        ///New time: {2}.
        /// </summary>
        internal static string ReplayAttack {
            get {
                return ResourceManager.GetString("ReplayAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fully qualified/rooted path is required..
        /// </summary>
        internal static string RootedPathRequired {
            get {
                return ResourceManager.GetString("RootedPathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find data.tar.gz inside Ruby Gem file..
        /// </summary>
        internal static string RubyGemInvalid {
            get {
                return ResourceManager.GetString("RubyGemInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature file already exists..
        /// </summary>
        internal static string SignatureAldreadyExists {
            get {
                return ResourceManager.GetString("SignatureAldreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to establish connection with StoreService..
        /// </summary>
        internal static string StoreServiceCommunicationProblem {
            get {
                return ResourceManager.GetString("StoreServiceCommunicationProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add implementation to a store..
        /// </summary>
        internal static string UnableToAddImplementionToStore {
            get {
                return ResourceManager.GetString("UnableToAddImplementionToStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find a secret key with the specified name..
        /// </summary>
        internal static string UnableToFindSecretKey {
            get {
                return ResourceManager.GetString("UnableToFindSecretKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified MIME type is unknown..
        /// </summary>
        internal static string UnknownMimeType {
            get {
                return ResourceManager.GetString("UnknownMimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passphrase you entered is incorrect..
        /// </summary>
        internal static string WrongPassphrase {
            get {
                return ResourceManager.GetString("WrongPassphrase", resourceCulture);
            }
        }
    }
}
