//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroInstall.Model.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZeroInstall.Model.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string must be in the form &quot;os-cpu&quot;..
        /// </summary>
        internal static string ArchitectureStringFormat {
            get {
                return ResourceManager.GetString("ArchitectureStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dot-separated list may only contain decimal numbers..
        /// </summary>
        internal static string MustBeDottedList {
            get {
                return ResourceManager.GetString("MustBeDottedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be a specific CPU (not &quot;All&quot; or &quot;Unknown&quot;)..
        /// </summary>
        internal static string MustBeSpecificCPU {
            get {
                return ResourceManager.GetString("MustBeSpecificCPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be a specific operating system (not &quot;All&quot; or &quot;Unknown&quot;)..
        /// </summary>
        internal static string MustBeSpecificOS {
            get {
                return ResourceManager.GetString("MustBeSpecificOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version number may only contain dot-separated decimals and modifier strings..
        /// </summary>
        internal static string MustBeValidVersionPart {
            get {
                return ResourceManager.GetString("MustBeValidVersionPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version number must begin with a list of dot-separated decimals..
        /// </summary>
        internal static string MustStartWithDottedList {
            get {
                return ResourceManager.GetString("MustStartWithDottedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The modifier is unknown..
        /// </summary>
        internal static string UnknownModifier {
            get {
                return ResourceManager.GetString("UnknownModifier", resourceCulture);
            }
        }
    }
}
