//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument may not be less than zero..
        /// </summary>
        internal static string ArgMustNotBeNegative {
            get {
                return ResourceManager.GetString("ArgMustNotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array is too small to hold all of the items..
        /// </summary>
        internal static string ArrayTooSmall {
            get {
                return ResourceManager.GetString("ArrayTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to pass at least two values!.
        /// </summary>
        internal static string AtLeast2Values {
            get {
                return ResourceManager.GetString("AtLeast2Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparand is not of the correct type..
        /// </summary>
        internal static string BadComparandType {
            get {
                return ResourceManager.GetString("BadComparandType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection cannot be added to itself..
        /// </summary>
        internal static string CannotAddCollectionToSelf {
            get {
                return ResourceManager.GetString("CannotAddCollectionToSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The \&quot;{0}\&quot; collection is read-only and cannot be modified..
        /// </summary>
        internal static string CannotModifyCollection {
            get {
                return ResourceManager.GetString("CannotModifyCollection", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ClearButton {
            get {
                object obj = ResourceManager.GetObject("ClearButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection is empty..
        /// </summary>
        internal static string CollectionIsEmpty {
            get {
                return ResourceManager.GetString("CollectionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content archives were already loaded.
        /// </summary>
        internal static string ContentArchivesAlreadyLoaded {
            get {
                return ResourceManager.GetString("ContentArchivesAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create XmlWriter..
        /// </summary>
        internal static string FailedToCreateXmlWriter {
            get {
                return ResourceManager.GetString("FailedToCreateXmlWriter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The load factor must be between 0.25 and 0.95..
        /// </summary>
        internal static string InvalidLoadFactor {
            get {
                return ResourceManager.GetString("InvalidLoadFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item is already in a pool!.
        /// </summary>
        internal static string ItemAlreadyInPool {
            get {
                return ResourceManager.GetString("ItemAlreadyInPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key was already present in the dictionary..
        /// </summary>
        internal static string KeyAlreadyPresent {
            get {
                return ResourceManager.GetString("KeyAlreadyPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key was not found in the collection..
        /// </summary>
        internal static string KeyNotFound {
            get {
                return ResourceManager.GetString("KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list may not be read only..
        /// </summary>
        internal static string ListIsReadOnly {
            get {
                return ResourceManager.GetString("ListIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! All your changes to this file will be lost. Do you wish to continue?.
        /// </summary>
        internal static string LoseChangesAsk {
            get {
                return ResourceManager.GetString("LoseChangesAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No
        ///Keep the changes.
        /// </summary>
        internal static string LoseChangesNo {
            get {
                return ResourceManager.GetString("LoseChangesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes
        ///Delete the changes.
        /// </summary>
        internal static string LoseChangesYes {
            get {
                return ResourceManager.GetString("LoseChangesYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum amount of elements in the collection has been exceeded..
        /// </summary>
        internal static string MaxElementsExceeded {
            get {
                return ResourceManager.GetString("MaxElementsExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Min value may not be larger than the Max value..
        /// </summary>
        internal static string MinLargerMax {
            get {
                return ResourceManager.GetString("MinLargerMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The get accessor of the indexer must be overridden..
        /// </summary>
        internal static string MustOverrideIndexerGet {
            get {
                return ResourceManager.GetString("MustOverrideIndexerGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The set accessor of the indexer must be overridden..
        /// </summary>
        internal static string MustOverrideIndexerSet {
            get {
                return ResourceManager.GetString("MustOverrideIndexerSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method must be overridden or re-implemented in the derived class..
        /// </summary>
        internal static string MustOverrideOrReimplement {
            get {
                return ResourceManager.GetString("MustOverrideOrReimplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is currently no active mod..
        /// </summary>
        internal static string NoModActive {
            get {
                return ResourceManager.GetString("NoModActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following game data file could not be found:.
        /// </summary>
        internal static string NotFoundGameContentFile {
            get {
                return ResourceManager.GetString("NotFoundGameContentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game data directory could not be found:.
        /// </summary>
        internal static string NotFoundGameDataDir {
            get {
                return ResourceManager.GetString("NotFoundGameDataDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mod directory could not be found:.
        /// </summary>
        internal static string NotFoundModDataDir {
            get {
                return ResourceManager.GetString("NotFoundModDataDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no XML data found in the file..
        /// </summary>
        internal static string NoXmlDataInFile {
            get {
                return ResourceManager.GetString("NoXmlDataInFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument is outside the range of this View..
        /// </summary>
        internal static string OutOfViewRange {
            get {
                return ResourceManager.GetString("OutOfViewRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command cannot be performed again until the undo command has been performed..
        /// </summary>
        internal static string RedoNotAvailable {
            get {
                return ResourceManager.GetString("RedoNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset is not supported on this enumerator..
        /// </summary>
        internal static string ResetNotSupported {
            get {
                return ResourceManager.GetString("ResetNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert.
        /// </summary>
        internal static string Revert {
            get {
                return ResourceManager.GetString("Revert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of targets must be equal to Length of oldValues.
        /// </summary>
        internal static string TargetsOldValuesLength {
            get {
                return ResourceManager.GetString("TargetsOldValuesLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file could not be deleted..
        /// </summary>
        internal static string UnableToDelete {
            get {
                return ResourceManager.GetString("UnableToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This undo command cannot be performed until the actual command has been performed..
        /// </summary>
        internal static string UndoNotAvailable {
            get {
                return ResourceManager.GetString("UndoNotAvailable", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Warning {
            get {
                object obj = ResourceManager.GetObject("Warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X and Y must be powers of 2.
        /// </summary>
        internal static string XandYpow2 {
            get {
                return ResourceManager.GetString("XandYpow2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
