
// This file has been generated by the GUI designer. Do not modify.
namespace ZeroInstall.Commands.Gtk
{
	public partial class MainWindow
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ZeroInstall.Commands.Gtk.MainWindow
			this.Name = "ZeroInstall.Commands.Gtk.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
