//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroInstall.Updater.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZeroInstall.Updater.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying files....
        /// </summary>
        public static string CopyFiles {
            get {
                return ResourceManager.GetString("CopyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting obsolete files....
        /// </summary>
        public static string DeleteFiles {
            get {
                return ResourceManager.GetString("DeleteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for all Zero Install instances to end....
        /// </summary>
        public static string MutexWait {
            get {
                return ResourceManager.GetString("MutexWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running as administrator....
        /// </summary>
        public static string RerunElevated {
            get {
                return ResourceManager.GetString("RerunElevated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-compiling .NET assemblies for faster application startup....
        /// </summary>
        public static string RunNgen {
            get {
                return ResourceManager.GetString("RunNgen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source directory does not exist..
        /// </summary>
        public static string SourceMissing {
            get {
                return ResourceManager.GetString("SourceMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Zero Install Store Service....
        /// </summary>
        public static string StartService {
            get {
                return ResourceManager.GetString("StartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping Zero Install Store Service....
        /// </summary>
        public static string StopService {
            get {
                return ResourceManager.GetString("StopService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again?.
        /// </summary>
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating registry....
        /// </summary>
        public static string UpdateRegistry {
            get {
                return ResourceManager.GetString("UpdateRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong number of arguments.
        ///Usage: {0}.
        /// </summary>
        public static string WrongNoArguments {
            get {
                return ResourceManager.GetString("WrongNoArguments", resourceCulture);
            }
        }
    }
}
